[package]
name = "rpitest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = { version = "0.17", features = ["hal"] }
#rumqttc = "0.24.0"
libc = "0.2"
ads1x1x = "0.2"
nb = "1.1.0"
